---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    networks:
      - name: clickhouse
  - name: instance-2
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    networks:
      - name: clickhouse
  - name: instance-3
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    networks:
      - name: clickhouse
provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory
  playbooks:
    converge: ../resources/converge.yml
verifier:
  name: testinfra
